### PR TITLE
Add docker

### PR DESCRIPTION
**Pull request by RodolfoSilva**
I think we can use docker to help new contributors start the environment.

### CODE REVIEW

**Comment by cleristonos** [comment]
i agree! I want start contribute and a docker it's amazing to break inertia

**Comment by cleristonos** [comment]
@RodolfoSilva you can add a start instructions into readme.md to docker

**Comment by di3goleite** [comment]
OMG!

**Comment by RodolfoSilva** [comment]
@cleristonos  done

**Pull request merged**
