### PR TITLE
Adding CI configuration

### LINKED ISSUE #6: [Infra] Integrate with some CI
Possible CIs ?
- [Wercker](http://www.wercker.com/)
- [TravisCI](https://travis-ci.org/)
- [CircleCI](https://circleci.com/)

### PR DESCRIPTION
**Pull request by rafaelverger**
Closes #6

### CODE REVIEW

**Comment by rafaelverger** [comment]
**Travis** took **3m15s** to run `npm install` + `npm test`: [build link](https://travis-ci.org/rafaelverger/overflow-news/builds/358528916)
image

**Comment by rafaelverger** [comment]
**Wercker** took **19s** to run `npm install` + `npm test`: [build link](https://app.wercker.com/rafaelverger/overflow-news/runs/build/5ab934bb3ada9c000166f413)
image

**Comment by rafaelverger** [comment]
**Circle** took **4min13s** to run `npm install` + `npm test`: [build link](https://circleci.com/gh/rafaelverger/overflow-news/1#build-timing/containers/0)
image

**Comment by rafaelverger** [comment]
- Wercker uses a global cache for npm modules and this is why it finishes the build so quickly and in both (first and second) builds it took only 19s
- Travis took 2min41s in its second build
- Circle took 1min44s in its second build

I vote for wercker's integration. Besides this caching advantage (some times it could be a downside) I really enjoy werckers ecossystems and compatibility with docker/containers

Vote here for choose a CI and then I will remove the other configs:
- Wercker 🎉 
- Travis 👍 
- Circle 😄

**Comment by clucasalcantara** [comment]
We could override wercker’s cache very easily, and for overflow news data types I don’t think that cache will be a problem in the future.

**Comment by rafaelverger** [comment]
Yeah... the wercker's cache were a problem to one of my projects (I have more than 15 running on wercker) and that's why I've pointed that it could be a downside.. but it's very simple to override it :)

**Comment by di3goleite** [comment]
Wercker <3 👍

**Comment by di3goleite** [comment]
Thank you so much @rafaelverger !!! 🎉 
The code is merged. I'll setup Wercker late tonight. ❤️

**Pull request merged**
